services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: delivery_app_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  app:
    image: fairbearof/delivery-app:latest
    container_name: my-java-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/delivery_app_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    volumes:
      - ./docker-compose.env:/app/.env
    command: ["sh", "-c", "sleep 10 && java -jar app.jar"]
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: